branches:
  only:
    - master

language: node_js

matrix:
  include:
    - os: osx
      language: node_js
      node_js:
        - node
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
node_js:
  - 11

cache:
  # yarn: true
  directories:
    - node_modules
    - app/node_modules
    - $(npm config get prefix)/lib/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - yarn 

script:
  - yarn dist

addons:
  artifacts:
    # ...
    paths:
      - dist/**